window.GF = {
  screens:{}, currentRole:null, currentScreen:null,
  roles:{
    admin:{label:'Quản trị viên',name:'Nguyễn Minh Khoa',home:'admin-dashboard',icon:'bi-shield-check'},
    receptionist:{label:'Lễ tân',name:'Nguyễn Thị Mai',home:'receptionist-dashboard',icon:'bi-headset'},
    cashier:{label:'Thu ngân',name:'Trần Ngọc Anh',home:'cashier-dashboard',icon:'bi-cash-coin'},
    pt:{label:'Huấn luyện viên',name:'Phạm Minh Tuấn',home:'pt-dashboard',icon:'bi-person-arms-up'},
    equipment:{label:'Quản lý thiết bị',name:'Lê Quốc Huy',home:'equipment-dashboard',icon:'bi-tools'},
    member:{label:'Hội viên',name:'Nguyễn Văn An',home:'member-home',icon:'bi-person-heart'}
  },
  menus:{
    admin:[['TỔNG QUAN','admin-dashboard','bi-grid-1x2','Dashboard'],['QUẢN LÝ','admin-members','bi-people','Hội viên'],['','admin-packages','bi-box-seam','Gói tập'],['','admin-memberships','bi-credit-card','Thẻ & Đăng ký'],['','admin-checkin','bi-qr-code-scan','Điểm danh'],['','admin-schedule','bi-calendar3','Lịch PT'],['','admin-payments','bi-receipt','Thanh toán'],['PHÂN TÍCH','admin-reports','bi-bar-chart','Báo cáo'],['VẬN HÀNH','admin-equipment','bi-tools','Thiết bị'],['','admin-staff','bi-person-badge','Nhân sự'],['','admin-system','bi-gear','Hệ thống'],['','admin-settings','bi-sliders','Cài đặt']],
    receptionist:[['VẬN HÀNH','receptionist-dashboard','bi-grid','Dashboard vận hành'],['','receptionist-members','bi-people','Hội viên'],['','receptionist-memberships','bi-card-checklist','Đăng ký gói/thẻ'],['','receptionist-checkin','bi-qr-code-scan','Điểm danh'],['','receptionist-pt-schedule','bi-calendar3','Lịch PT'],['','receptionist-payments','bi-cash-coin','Thanh toán cơ bản'],['HỖ TRỢ','receptionist-report-issue','bi-exclamation-triangle','Báo sự cố thiết bị'],['','receptionist-support','bi-headset','Hỗ trợ khách']],
    cashier:[['TÀI CHÍNH','cashier-dashboard','bi-grid','Dashboard tài chính'],['','cashier-payments','bi-cash-stack','Thanh toán'],['','cashier-invoice','bi-receipt','Hóa đơn'],['','cashier-history','bi-clock-history','Lịch sử giao dịch'],['DANH MỤC','cashier-packages','bi-box-seam','Gói tập'],['','cashier-reports','bi-bar-chart','Báo cáo cơ bản']],
    pt:[['HUẤN LUYỆN','pt-dashboard','bi-grid','Dashboard PT'],['','pt-schedule','bi-calendar3','Lịch của tôi'],['','pt-bookings','bi-calendar-plus','Yêu cầu đặt lịch'],['','pt-members','bi-people','Hội viên phụ trách'],['','pt-roadmap','bi-signpost-split','Lộ trình tập'],['','pt-confirm-session','bi-check2-square','Xác nhận buổi tập'],['TÀI KHOẢN','pt-salary','bi-wallet2','Lương của tôi'],['','pt-profile','bi-person-circle','Hồ sơ cá nhân']],
    equipment:[['THIẾT BỊ','equipment-dashboard','bi-grid','Dashboard thiết bị'],['','equipment-list','bi-tools','Danh sách thiết bị'],['','equipment-issues','bi-exclamation-diamond','Báo cáo sự cố'],['','equipment-schedule','bi-calendar-event','Lịch bảo trì'],['','equipment-tickets','bi-clipboard2-check','Phiếu bảo trì'],['','equipment-history','bi-clock-history','Lịch sử bảo trì']],
    member:[['CÁ NHÂN','member-home','bi-house','Trang chủ'],['','member-packages','bi-box-seam','Gói tập'],['','member-card','bi-credit-card-2-front','Thẻ của tôi'],['','member-checkin','bi-qr-code','QR Check-in'],['','member-book-pt','bi-calendar-plus','Đặt lịch PT'],['','member-schedule','bi-calendar3','Lịch tập của tôi'],['','member-payments','bi-receipt','Thanh toán/Hóa đơn'],['TÀI KHOẢN','member-profile','bi-person','Hồ sơ cá nhân'],['','member-body','bi-activity','Chỉ số cơ thể']]
  },
  fmt:{currency:n=>new Intl.NumberFormat('vi-VN',{style:'currency',currency:'VND'}).format(n||0),date:d=>new Date(d).toLocaleDateString('vi-VN')},
  initials:name=>(name||'GF').trim().split(/\s+/).slice(-2).map(x=>x[0]).join('').toUpperCase(),
  renderAvatar(name,size=36){return `<span class="avatar" style="width:${size}px;height:${size}px;font-size:${Math.max(10,size*.34)}px">${this.initials(name)}</span>`},
  status(status){const map={active:['Đang hoạt động','success'],expiring:['Sắp hết hạn','warning'],paused:['Tạm ngưng','warning'],expired:['Hết hạn','danger'],completed:['Hoàn thành','success'],pending:['Chờ xác nhận','warning'],maintenance:['Đang bảo trì','warning'],inspection:['Đang kiểm tra','primary'],broken:['Hỏng','danger'],success:['Thành công','success']};const x=map[status]||[status,'secondary'];return `<span class="badge bg-${x[1]}-subtle text-${x[1]}">${x[0]}</span>`},
  renderBadge(status){return this.status(status)},
  renderEmptyState({icon='bi-inbox',title='Không có dữ liệu',message='Dữ liệu mới sẽ được hiển thị tại đây.'}={}){return `<div class="empty-state"><i class="bi ${icon}"></i><h3>${title}</h3><p>${message}</p></div>`},
  navigate(screen,params){ if(!this.screens[screen]) screen=this.roles[this.currentRole]?.home||'admin-dashboard'; this.currentScreen=screen; history.replaceState({},'',`#${screen}`); this.renderNav(); this.screens[screen]?.(params||{}); document.getElementById('main-content')?.scrollTo(0,0); },
  login(role){this.currentRole=role;sessionStorage.setItem('gf-role',role);document.getElementById('auth-screen').classList.add('hidden');document.getElementById('app-shell').classList.remove('hidden');this.renderShell();this.navigate(this.roles[role].home);},
  logout(){sessionStorage.removeItem('gf-role');this.currentRole=null;document.getElementById('app-shell').classList.add('hidden');document.getElementById('auth-screen').classList.remove('hidden');this.screens.login();},
  switchRole(role){this.login(role);this.toast.success(`Đã chuyển sang vai trò ${this.roles[role].label}`)},
  renderShell(){this.renderNav();const u=this.roles[this.currentRole];document.getElementById('topbar').innerHTML=`<button class="icon-btn mobile-menu" onclick="document.getElementById('sidebar').classList.toggle('mobile-open')"><i class="bi bi-list"></i></button><div class="topbar-search"><i class="bi bi-search"></i><input placeholder="Tìm hội viên, hóa đơn, thiết bị..."></div><div class="topbar-actions"><button class="icon-btn"><i class="bi bi-bell"></i><span class="notification-dot"></span></button><div class="user-menu" onclick="GF.logout()">${this.renderAvatar(u.name,38)}<div class="user-copy"><div class="user-name">${u.name}</div><div class="user-role">${u.label} · Đăng xuất</div></div><i class="bi bi-chevron-down text-muted"></i></div></div>`},
  renderNav(){if(!this.currentRole)return;const items=this.menus[this.currentRole]||[];document.getElementById('sidebar-nav').innerHTML=items.map(([section,id,icon,label])=>`${section?`<div class="nav-section-label">${section}</div>`:''}<button class="nav-item ${this.currentScreen===id?'active':''}" onclick="GF.navigate('${id}');document.getElementById('sidebar').classList.remove('mobile-open')"><i class="bi ${icon}"></i><span class="nav-label">${label}</span></button>`).join('')},
  toggleSidebar(){document.getElementById('sidebar').classList.toggle('collapsed')},
  modal:{hide(){document.getElementById('modal-root').classList.add('hidden');document.getElementById('modal-backdrop').classList.add('hidden')},show(html){document.getElementById('modal-root').innerHTML=html;document.getElementById('modal-root').classList.remove('hidden');document.getElementById('modal-backdrop').classList.remove('hidden')},confirm(o){this.show(`<div class="modal-dialog"><div class="modal-head"><h4>${o.title||'Xác nhận'}</h4><button onclick="GF.modal.hide()"><i class="bi bi-x-lg"></i></button></div><div class="modal-content-body"><div class="alert alert-${o.type==='danger'?'danger':'warning'}"><i class="bi bi-exclamation-triangle me-2"></i>${o.message}</div></div><div class="modal-actions"><button class="btn btn-outline-secondary" onclick="GF.modal.hide()">Hủy</button><button id="modal-confirm" class="btn btn-${o.type||'primary'}">${o.confirmText||'Xác nhận'}</button></div></div>`);document.getElementById('modal-confirm').onclick=()=>{this.hide();o.onConfirm?.()}}},
  toast:{show(msg,type='success'){const el=document.createElement('div');el.className=`toast-item ${type}`;el.innerHTML=`<i class="bi ${type==='success'?'bi-check-circle-fill text-success':type==='warning'?'bi-exclamation-circle-fill text-warning':'bi-x-circle-fill text-danger'}"></i><div><strong>${type==='success'?'Thành công':type==='warning'?'Lưu ý':'Có lỗi xảy ra'}</strong><div class="text-secondary text-sm">${msg}</div></div>`;document.getElementById('toast-root').append(el);setTimeout(()=>el.remove(),3200)},success(m){this.show(m)},warning(m){this.show(m,'warning')},error(m){this.show(m,'error')}}
};
