/* Shared interactions: contextual actions, notifications and member tools. */
(function(){
  GF.pageParents={
    'admin-member-detail':'admin-members','admin-member-form':'admin-members','admin-package-detail':'admin-packages','admin-package-form':'admin-packages','admin-membership-form':'admin-memberships','admin-membership-detail':'admin-memberships','admin-checkin-quick':'admin-checkin','admin-checkin-detail':'admin-checkin','admin-schedule-form':'admin-schedule','admin-schedule-detail':'admin-schedule','admin-create-payment':'admin-payments','admin-equipment-form':'admin-equipment','admin-equipment-detail':'admin-equipment','admin-equipment-issue':'admin-equipment','admin-staff-form':'admin-staff','admin-staff-detail':'admin-staff','admin-roles':'admin-staff',
    'receptionist-membership-form':'receptionist-memberships','receptionist-payment-form':'receptionist-payments','receptionist-support-form':'receptionist-support',
    'cashier-create-payment':'cashier-payments','cashier-payment-result':'cashier-payments','cashier-invoice':'cashier-payments',
    'equipment-form':'equipment-list','equipment-schedule-form':'equipment-schedule','equipment-ticket-form':'equipment-tickets',
    'member-package-compare':'member-packages'
  };
  GF.addPageBackButton=function(){const main=document.getElementById('main-content'),parent=GF.pageParents[GF.currentScreen];if(!main||!parent||main.querySelector(':scope > .page-back-row'))return;const row=document.createElement('div');row.className='page-back-row';row.innerHTML=`<button class="page-back-btn" onclick="GF.navigate('${parent}')"><i class="bi bi-arrow-left"></i>Quay lại</button>`;main.prepend(row)};
  GF.cleanupPageControls=function(){const main=document.getElementById('main-content');if(!main)return;
    main.querySelectorAll('.page-header button').forEach(button=>{const text=button.textContent.trim().toLowerCase();if(text.includes('quay lại')||text.includes('hủy quy trình')||text.includes('hủy giao dịch')){const holder=button.parentElement;button.remove();if(holder&&holder!==main&&holder.children.length===0&&!holder.textContent.trim())holder.remove()}});
    main.querySelectorAll('button').forEach(button=>{if(button.disabled||button.closest('.page-back-row'))return;const hasAction=button.hasAttribute('onclick')||typeof button.onclick==='function';const type=(button.getAttribute('type')||'').toLowerCase();const isSubmit=type==='submit'||(!type&&button.closest('form'));if(!hasAction&&!isSubmit)button.remove()})
  };
  GF.enhancePageActions=function(){GF.addPageBackButton();document.querySelectorAll('.table tbody tr').forEach((row,index)=>{const last=row.lastElementChild;if(!last)return;last.querySelectorAll('button').forEach(button=>{if(button.getAttribute('onclick')||typeof button.onclick==='function')return;button.onclick=()=>GF.openContextActions({index,rowText:row.innerText,screen:GF.currentScreen})})});GF.cleanupPageControls()};
  GF.openContextActions=function({index=0,rowText='',screen=GF.currentScreen}={}){const id=(rowText.match(/(?:MV|HD|DK|TB|NV|BT|SC|HT|YCTT)\d+/)||[])[0]||`#${index+1}`;let actions=[];
    if(/member|members/.test(screen))actions=[['bi-eye','Xem chi tiết',()=>GF.toast.success(`Đã mở chi tiết ${id}`)],['bi-pencil','Chỉnh sửa',()=>GF.toast.success(`Đã mở biểu mẫu chỉnh sửa ${id}`)],['bi-card-checklist','Đăng ký/Gia hạn gói',()=>GF.toast.success(`Đã mở đăng ký cho ${id}`)],['bi-person-x','Tạm ngưng','danger',()=>GF.confirmContext(`Tạm ngưng ${id}`)]];
    else if(/payment|invoice|history/.test(screen))actions=[['bi-receipt','Xem hóa đơn',()=>GF.toast.success(`Đã mở hóa đơn ${id}`)],['bi-download','Tải PDF',()=>GF.toast.success(`Đã tải hóa đơn ${id}`)],['bi-envelope','Gửi hóa đơn',()=>GF.toast.success(`Đã gửi hóa đơn ${id}`)],['bi-arrow-counterclockwise','Hoàn tiền','danger',()=>GF.confirmContext(`Hoàn tiền giao dịch ${id}`)]];
    else if(/schedule|booking|session/.test(screen))actions=[['bi-eye','Xem lịch',()=>GF.toast.success(`Đã mở lịch ${id}`)],['bi-calendar2-week','Đổi lịch',()=>GF.toast.success(`Đã mở biểu mẫu đổi lịch ${id}`)],['bi-check-circle','Đánh dấu hoàn thành',()=>GF.toast.success(`Đã hoàn thành ${id}`)],['bi-x-circle','Hủy lịch','danger',()=>GF.confirmContext(`Hủy lịch ${id}`)]];
    else if(/equipment|ticket|issue|maintenance/.test(screen))actions=[['bi-eye','Xem thiết bị/Phiếu',()=>GF.toast.success(`Đã mở chi tiết ${id}`)],['bi-pencil','Chỉnh sửa',()=>GF.toast.success(`Đã mở chỉnh sửa ${id}`)],['bi-calendar-plus','Lập lịch bảo trì',()=>GF.toast.success(`Đã mở lịch bảo trì ${id}`)],['bi-exclamation-triangle','Báo cáo sự cố','danger',()=>GF.toast.warning(`Đã mở báo cáo sự cố ${id}`)]];
    else if(/staff|role/.test(screen))actions=[['bi-person','Xem hồ sơ',()=>GF.toast.success(`Đã mở hồ sơ ${id}`)],['bi-pencil','Chỉnh sửa nhân viên',()=>GF.toast.success(`Đã mở chỉnh sửa ${id}`)],['bi-shield-lock','Gán vai trò & Quyền',()=>GF.toast.success(`Đã mở phân quyền ${id}`)],['bi-lock','Khóa tài khoản','danger',()=>GF.confirmContext(`Khóa tài khoản ${id}`)]];
    else actions=[['bi-eye','Xem chi tiết',()=>GF.toast.success(`Đã mở chi tiết ${id}`)],['bi-pencil','Chỉnh sửa',()=>GF.toast.success(`Đã mở chỉnh sửa ${id}`)],['bi-download','Xuất dữ liệu',()=>GF.toast.success(`Đã xuất dữ liệu ${id}`)],['bi-archive','Lưu trữ','danger',()=>GF.confirmContext(`Lưu trữ ${id}`)]];
    GF.modal.show(`<div class="modal-dialog"><div class="modal-head"><div><h4>Thao tác</h4><p class="text-sm">${id}</p></div><button onclick="GF.modal.hide()"><i class="bi bi-x-lg"></i></button></div><div class="modal-content-body"><div class="d-grid gap-2">${actions.map((a,i)=>`<button class="btn ${a[2]==='danger'?'btn-outline-danger':'btn-outline-primary'}" id="context-action-${i}"><i class="bi ${a[0]}"></i>${a[1]}</button>`).join('')}</div></div></div>`);actions.forEach((a,i)=>document.getElementById(`context-action-${i}`).onclick=()=>{GF.modal.hide();(typeof a[2]==='function'?a[2]:a[3])()})};
  GF.confirmContext=message=>GF.modal.confirm({title:'Xác nhận thao tác',message:`Bạn có chắc muốn ${message.toLowerCase()}?`,type:'danger',confirmText:'Xác nhận',onConfirm:()=>GF.toast.success(`Đã ${message.toLowerCase()}`)});

  GF.notifications=[
    {icon:'bi-calendar-check',color:'#2563eb',title:'Lịch PT đã được xác nhận',text:'Buổi tập với PT Phạm Minh Tuấn lúc 16:00 ngày 15/07.',time:'5 phút trước',unread:true},
    {icon:'bi-credit-card',color:'#10b981',title:'Thanh toán thành công',text:'Hóa đơn HD26071401 trị giá 2.850.000 ₫ đã được phát hành.',time:'32 phút trước',unread:true},
    {icon:'bi-exclamation-triangle',color:'#f59e0b',title:'Gói tập sắp hết hạn',text:'Gói Basic của Trần Thị Bình sẽ hết hạn sau 14 ngày.',time:'1 giờ trước',unread:true},
    {icon:'bi-tools',color:'#ef4444',title:'Sự cố thiết bị mới',text:'Máy chạy bộ T-08 được báo cáo phát tiếng kêu bất thường.',time:'2 giờ trước',unread:false},
    {icon:'bi-person-plus',color:'#8b5cf6',title:'Hội viên mới',text:'Nguyễn Minh Anh vừa hoàn tất đăng ký tài khoản.',time:'Hôm qua',unread:false}
  ];
  GF.showNotifications=function(filter='all'){const visible=GF.notifications.map((n,i)=>({n,i})).filter(x=>filter==='all'||x.n.unread);GF.modal.show(`<div class="modal-dialog"><div class="modal-head"><div><h4>Thông báo</h4><p class="text-sm"><span>${GF.notifications.filter(x=>x.unread).length}</span> thông báo chưa đọc</p></div><button onclick="GF.modal.hide()"><i class="bi bi-x-lg"></i></button></div><div class="modal-content-body"><div class="d-flex justify-content-between align-items-center mb-3"><div class="d-flex gap-2"><button class="btn btn-sm ${filter==='all'?'btn-primary':'btn-outline-secondary'}" onclick="GF.showNotifications('all')">Tất cả</button><button class="btn btn-sm ${filter==='unread'?'btn-primary':'btn-outline-secondary'}" onclick="GF.showNotifications('unread')">Chưa đọc</button></div><button class="btn btn-sm btn-link" onclick="GF.markAllNotificationsRead()"><i class="bi bi-check2-all"></i>Đánh dấu đã đọc</button></div><div class="notification-list">${visible.length?visible.map(({n,i})=>`<div class="notification-item ${n.unread?'unread':''}" onclick="GF.readNotification(${i},'${filter}')"><span class="notification-icon" style="background:${n.color}18;color:${n.color}"><i class="bi ${n.icon}"></i></span><div class="notification-content"><div class="notification-title">${n.title}</div><div class="notification-text">${n.text}</div><div class="notification-time"><i class="bi bi-clock"></i> ${n.time}</div></div>${n.unread?'<span class="notification-unread-dot"></span>':''}</div>`).join(''):'<div class="empty-state"><i class="bi bi-bell-slash"></i><h3>Không còn thông báo chưa đọc</h3></div>'}</div></div><div class="modal-actions"><button class="btn btn-outline-secondary" onclick="GF.modal.hide()">Đóng</button></div></div>`)};
  GF.readNotification=function(index,filter='all'){GF.notifications[index].unread=false;GF.showNotifications(filter);GF.updateNotificationDot()};
  GF.markAllNotificationsRead=function(){GF.notifications.forEach(x=>x.unread=false);GF.showNotifications();GF.updateNotificationDot();GF.toast.success('Đã đánh dấu tất cả thông báo là đã đọc')};
  GF.updateNotificationDot=function(){const dot=document.getElementById('notification-dot');if(dot)dot.classList.toggle('hidden',!GF.notifications.some(x=>x.unread))};

  GF.openMemberQR=function(){GF.modal.show(`<div class="qr-fullscreen-card"><div class="d-flex justify-content-between align-items-center mb-4"><div class="text-left"><h3 style="font-size:20px">QR Check-in</h3><p class="text-sm">Nguyễn Văn An · MV001</p></div><button class="icon-btn" onclick="GF.modal.hide()"><i class="bi bi-x-lg"></i></button></div><div style="padding:20px;border:2px solid var(--primary-light);border-radius:18px"><i class="bi bi-qr-code" style="font-size:220px;line-height:1;color:#0f172a"></i></div><div class="alert alert-success mt-4"><i class="bi bi-shield-check me-2"></i>Mã đang hoạt động · Tự làm mới sau 00:42</div><button class="btn btn-outline-primary w-full" onclick="GF.modal.hide();GF.navigate('member-checkin')"><i class="bi bi-arrows-fullscreen"></i>Mở trang QR đầy đủ</button></div>`)};
  const memberHome=GF.screens['member-home'];GF.screens['member-home']=function(p){memberHome(p);const button=document.querySelector('.member-hero .btn');if(button)button.onclick=()=>GF.openMemberQR()};

  GF.screens['member-package-compare']=function(){const packages=GFData.packages;const rows=[['Giá gói',...packages.map(p=>GF.fmt.currency(p.price))],['Thời hạn',...packages.map(p=>p.duration)],['Không giới hạn lượt tập','Có','Có','Có'],['Tủ đồ cá nhân','Có','Có','Có'],['Đo chỉ số cơ thể','Có','Có','Có'],['Buổi PT cá nhân','—','4 buổi','12 buổi'],['Xông hơi & Lớp nhóm','—','Có','Có'],['Khăn tập và nước','—','—','Miễn phí']];document.getElementById('main-content').innerHTML=`${GF.screenHeader('So sánh gói tập','Đối chiếu giá và quyền lợi để chọn gói phù hợp','<button class="btn btn-outline-secondary" onclick="GF.navigate(\'member-packages\')"><i class="bi bi-arrow-left"></i>Quay lại</button>')}<div class="card"><div class="permissions-matrix"><table class="permissions-table"><thead><tr><th>Quyền lợi</th>${packages.map(p=>`<th><div class="package-card-icon" style="margin:0 auto 8px;background:${p.color}18;color:${p.color}"><i class="bi bi-gem"></i></div><strong class="text-primary">${p.name}</strong>${p.popular?'<div><span class="badge bg-primary-subtle text-blue mt-2">Phổ biến</span></div>':''}</th>`).join('')}</tr></thead><tbody>${rows.map((r,ri)=>`<tr><td>${r[0]}</td>${r.slice(1).map(x=>`<td>${x==='Có'?'<i class="bi bi-check-circle-fill text-success"></i>':x==='—'?'<span class="text-muted">—</span>':`<strong class="${ri===0?'text-blue':''}">${x}</strong>`}</td>`).join('')}</tr>`).join('')}<tr><td></td>${packages.map(p=>`<td><button class="btn ${p.popular?'btn-primary':'btn-outline-primary'}" onclick="GF.startMemberPayment('${p.id}')">Chọn ${p.name}</button></td>`).join('')}</tr></tbody></table></div></div><div class="alert alert-info mt-4"><i class="bi bi-lightbulb me-2"></i>Gói Premium phù hợp nhất nếu bạn cần PT hướng dẫn và thường xuyên tham gia lớp nhóm.</div>`};
  const memberPackages=GF.screens['member-packages'];GF.screens['member-packages']=function(p){memberPackages(p);const compare=document.querySelector('.page-header .btn-outline-primary');if(compare)compare.onclick=()=>GF.navigate('member-package-compare')};
})();
